package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AthenaMandatoryChecks_athena_public'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AthenaMandatoryChecks_athena_public")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "Athena_AthenaPublic"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "zxx24d3eb84f48caad36dc56a3252875b70b7fd09cd46cb8ab54153e54fc1042983f410212252a6a0cf775d03cbe80d301b"
                    }
                }
            }
        }
        feature1.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:c3f84f17-e571-495d-a804-ea7a25b20d89"
                }
            }
        }
        val feature2 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "Athena_AthenaPublic"
                publisher = upsource {
                    serverUrl = "https://upsource.getathena.ml"
                    projectId = "ATHENA"
                    userName = "admin"
                    password = "zxx771e317223635f9b139d6aec1e0d771ca7964e61aa6cbd40604de29877cb04b50a8d93941b3b5f7ce52d4fa5a8dfbd56ebe49af0469bf9f4626f1248aebc6d0d775d03cbe80d301b"
                }
            }
        }
        feature2.apply {
            publisher = upsource {
                serverUrl = "https://upsource.getathena.ml"
                projectId = "ATHENA"
                userName = "admin"
                password = "credentialsJSON:3185188d-44f7-4583-b5f5-3b43968674f3"
            }
        }
    }
}
