package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MandatoryChecks'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MandatoryChecks")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "zxx1bfacd1e0d69bcbff375fbbc5dfdcebcf0b349a3e1c4d89ea8a537816b12b1fd074ca14f942bc176775d03cbe80d301b"
                    }
                }
            }
        }
        feature1.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:613b2fe6-e338-45b7-99e7-a9f5f18ab9a3"
                }
            }
        }
        val feature2 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                publisher = upsource {
                    serverUrl = "https://upsource.getathena.ml"
                    projectId = "ATHENA"
                    userName = "admin"
                    password = "zxx771e317223635f9b139d6aec1e0d771ca7964e61aa6cbd40604de29877cb04b50a8d93941b3b5f7ce52d4fa5a8dfbd56ebe49af0469bf9f4626f1248aebc6d0d775d03cbe80d301b"
                }
            }
        }
        feature2.apply {
            publisher = upsource {
                serverUrl = "https://upsource.getathena.ml"
                projectId = "ATHENA"
                userName = "admin"
                password = "credentialsJSON:fd1cd3ea-0d5e-4a43-b9cc-9f55df932cd7"
            }
        }
    }
}
