package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ProjectFeature
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.YouTrackIssueTracker
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.youtrack
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<ProjectFeature> {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_15"
                param("clientId", "358302cb895dfde1a3e8")
                param("defaultTokenScope", "public_repo,repo,repo:status,write:repo_hook")
                param("displayName", "GitHub.com")
                param("gitHubUrl", "https://github.com/")
                param("providerType", "GitHub")
                param("secure:clientSecret", "zxxf3671e4259734f488a8f1f91d8699587bb6ee3dfdc7e9b8ceb90ae4ec2aa6230abe6753900b2ba4f775d03cbe80d301b")
            }
        }
        feature1.apply {
            param("secure:clientSecret", "credentialsJSON:968d931a-8103-458c-be90-8bd59b758795")
        }
        val feature2 = find<YouTrackIssueTracker> {
            youtrack {
                id = "PROJECT_EXT_2"
                displayName = "YouTrack"
                host = "https://youtrack.getathena.ml"
                userName = ""
                password = ""
                projectExtIds = "athena"
                accessToken = "zxx1333982c092e489ffe59a53bc2407b3915d355dffe56a396121652b257197741a1421a4daaa4fb92b8e202cb168c199f4cd4d5132b6840d9c328b1b5f1d960a3"
                param("authType", "accesstoken")
            }
        }
        feature2.apply {
            accessToken = "credentialsJSON:c62e4f54-04c1-4395-af81-71b19371fab0"
        }
        val feature3 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_3"
                name = "Gitlab"
                url = "https://registry.gitlab.com"
                userName = "athenamlbot"
                password = "credentialsJSON:53380671-6863-45e8-8bb2-3a3f8a17b2bc"
            }
        }
        feature3.apply {
            password = "credentialsJSON:61429fc2-1691-4c61-9957-e312bbabfc3c"
        }
    }
}
